const keyPossmessage = {
  CAN_POP: 'canPop',
  VOUCHER_ADDED: 'voucherAdded'
}

const MULTI_MODE = {
  SINGLE: 1,
  MULTI: 2
}

const ONE_HUNDRED_PERCENT = 100
const WITDH_OF_BORDER_DOTS = 4
const PADDING_OF_TICKET_DETAIL = 8

const STATUS_OF_VOUCHER = {
  FIXED_AMOUNT: 'FIXED_AMOUNT',
  PERCENT_MAX_AMOUNT: 'PERCENT_MAX_AMOUNT',
  PERCENT_UNLIMITED: 'PERCENT_UNLIMITED'
} as const

const STATUS_OF_VOUCHER_APPLY = {
  APPLY: 1,
  REMOVE: 0
} as const

export { keyPossmessage, MULTI_MODE, ONE_HUNDRED_PERCENT, WITDH_OF_BORDER_DOTS, PADDING_OF_TICKET_DETAIL, STATUS_OF_VOUCHER, STATUS_OF_VOUCHER_APPLY }
